### ISSUE TITLE
Needs to support asymmetric key signatures over shared secrets

### ISSUE THREAD

**Issue by Prandium** [progrium/ruby-jwt#46]
Currently, you are using a shared secret to validate the signature of the JWT messages. This entirely defeats the purpose of signing the message and would only be suitable if you were encrypting and not signing the message. The idea behind signing a message is that only the originator can generate the signature and that signature can be validated but not forged. In your implementation any node that needs to validate a signature must in turn be able to forge new ones, because it must know the shared secret.

Therefore, ruby-jwt should allow for the use of asymmetric key based signature generation and checking as outlined in the ruby stdlib OpenSSL documentation here: http://ruby-doc.org/stdlib-2.0/libdoc/openssl/rdoc/OpenSSL.html#module-OpenSSL-label-Signatures. This will allow JWT consumers to verify requests without the ability to forge new ones.

**Comment by kurtisnelson** [comment]
This should get put in the README, I had to google to find this.

**Comment by toshe** [comment]
contributing is not a crime, you know ;)

**Comment by excpt** [comment]
@kurtisnelson Thanks for bringing this up again. :)

The README / documentation really needs some updates. Working on it this weekend.

**Comment by excpt** [comment]
@Prandium I improved the documentation and added a better example.
