### ISSUE TITLE
What is the reason behind stripping the = in base64 encoding?

### ISSUE THREAD

**Issue by dmitrinesterenko** [progrium/ruby-jwt#54]
Hi All,

Curious what's the reason behind stripping the = padding that results in base64 encoding?   https://github.com/progrium/ruby-jwt/blob/85c7c8813e064ecf3d07ac799cc478eb413c4e48/lib/jwt.rb#L46

**Comment by excpt** [comment]
It's defined that way in the JOSE specifications to be compatible with different systems.

**Comment by dmitrinesterenko** [comment]
Ok thank you for the explanation, was surprised to not see '=' as it seems like a slight redefinition of base64encoding.
