### ISSUE TITLE
Fix either README or source code

### ISSUE THREAD

**Issue by AlexParamonov** [progrium/ruby-jwt#78]
I found that README has incorrect (not yet implemented) examples.
I do use the `iss` check in the app and implemented it using my wrapper class.

After the 1.5 released, I removed the wrapper and tested the jwt gem. It appears that it requires special "setup" before:
https://github.com/progrium/ruby-jwt/commit/5c09aadc7c9e94eeb319e36a2d5a98efc607149f#commitcomment-11125584

**Comment by excpt** [comment]
@AlexParamonov I updated the docs. I ran all the code snippets. Will you review the changes?

**Comment by AlexParamonov** [comment]
@excpt looks good. We can close the issue now
