### ISSUE TITLE
Doc mismatch: uninitialized constant JWT::ExpiredSignature

### ISSUE THREAD

**Issue by rjharmon** [progrium/ruby-jwt#79]
Readme says to look for JWT::ExpiredSignature, but the code doesn't have such an exception class defined.  It just throws a generic decoding error.

**Comment by excpt** [comment]
I cannot reproduce the error. When using an invalid exp claim in the token it will raise a correct JWT::ExpiredSignature error.

Can you please provide sample code and which version of the jwt gem you are using?

**Comment by rjharmon** [comment]
Apologies.  I had been Gemfile.lock'd into an old version via a previously-unknown secondary dependency on this Gem.  Updated that other dep, now I get a modern jwt gem.  

Thank you!
